include: package:lints/recommended.yaml

# https://dart.dev/tools/linter-rules
linter:
  rules:
    # async just slows us down since this is a single-thread script
    avoid_slow_async_io: true
    unnecessary_async: true
