name: adil192_linux
description: A config collection for my personal computers
version: 0.0.1
repository: https://github.com/adil192/adil192-linux

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.4.2
  hooks: ^1.0.2
  http: ^1.6.0
  native_toolchain_rust: ^1.0.3

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.1.0
