import 'dart:io';

import 'package:adil192_linux/src/cosmic_theme_bindings.g.dart';
export 'package:adil192_linux/src/cosmic_theme_bindings.g.dart' hide get_theme;

extension CosmicThemeCssVars on CosmicThemeFfi {
  List<(String name, Rgb value)> get cssVars {
    return [
      ('--cosmic-background-base', background_base),
      ('--cosmic-background-on', background_on),
      ('--cosmic-component-base', component_base),
      ('--cosmic-component-on', component_on),
      ('--cosmic-button-base', button_base),
      ('--cosmic-button-on', button_on),
    ];
  }
}

extension RgbaConverter on Rgb {
  String toHex() {
    return '#'
        '${r.toRadixString(16).padLeft(2, '0')}'
        '${g.toRadixString(16).padLeft(2, '0')}'
        '${b.toRadixString(16).padLeft(2, '0')}';
  }
}

void generateCosmicTokensCss() {
  final generatedCss = _generateCosmicTokensCssContent();
  final pwd = Platform.environment['PWD'] ?? '.';
  for (final cssFileName in ['userChrome.css', 'userContent.css']) {
    final dst = File('$pwd/assets/firefox-css/$cssFileName');
    var content = dst.readAsStringSync();
    content = content.replaceFirst(
      RegExp(r'\/\* START OF GENERATED CODE [^]* END OF GENERATED CODE \*\/'),
      '/* START OF GENERATED CODE */\n$generatedCss\n/* END OF GENERATED CODE */',
    );
    dst.writeAsStringSync(content);
  }
}

CosmicThemeFfi getLightCosmicTheme() => get_theme(false);
CosmicThemeFfi getDarkCosmicTheme() => get_theme(true);

String _generateCosmicTokensCssContent() {
  final light = getLightCosmicTheme();
  final dark = getDarkCosmicTheme();
  final buffer = StringBuffer();
  buffer.writeln(
    '/* Generated by adil192-linux. Do not edit as changes will be overwritten. */',
  );
  buffer.writeln(':root {');
  for (final (name, value) in light.cssVars) {
    buffer.writeln('  $name-light: ${value.toHex()};');
  }
  buffer.writeln();

  for (final (name, value) in dark.cssVars) {
    buffer.writeln('  $name-dark: ${value.toHex()};');
  }
  buffer.writeln();

  for (final (name, _) in light.cssVars) {
    buffer.writeln('  $name: var($name-light);');
  }
  buffer.writeln('  @media (-moz-content-prefers-color-scheme: dark) {');
  for (final (name, _) in dark.cssVars) {
    buffer.writeln('    $name: var($name-dark);');
  }
  buffer.writeln('  }');
  buffer.writeln();

  buffer.writeln(
    '  --cosmic-inactive-on: color(from var(--cosmic-background-on) srgb r g b / 0.5);',
  );
  buffer.write('}');
  return buffer.toString();
}
