// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<CosmicThemeFfi Function(ffi.Bool)>()
external CosmicThemeFfi get_theme(bool is_dark);

final class Rgb extends ffi.Struct {
  @ffi.Uint8()
  external int r;

  @ffi.Uint8()
  external int g;

  @ffi.Uint8()
  external int b;
}

final class CosmicThemeFfi extends ffi.Struct {
  external Rgb background_base;

  external Rgb background_on;

  external Rgb component_base;

  external Rgb component_on;

  external Rgb button_base;

  external Rgb button_on;
}
