/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Rgb {
  uint8_t r;
  uint8_t g;
  uint8_t b;
} Rgb;

typedef struct CosmicThemeFfi {
  struct Rgb background_base;
  struct Rgb background_on;
  struct Rgb component_base;
  struct Rgb component_on;
  struct Rgb button_base;
  struct Rgb button_on;
} CosmicThemeFfi;

struct CosmicThemeFfi get_theme(bool is_dark);
