[package]
name = "adil192-linux"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic", rev = "86dcf8af6cfcb3ab65e41649e4793f47c5595433", default-features = false }

[build-dependencies]
cbindgen = "0.29.0"
