[toolchain]
# WARNING: *do not* use `stable`, `beta`, or `nightly` (alone) for the channel!
# You must specify a version number/date in order to ensure reproducible builds.
channel = "1.94.0"

targets = [
  # Linux
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
]
